import { Message } from "@/components/ui/MessageCard";

// Dynamic billing period
const now = new Date();
const periodStart = new Date(now.getFullYear(), now.getMonth(), 1).toISOString().slice(0, 10);
const periodEnd = new Date(now.getFullYear(), now.getMonth() + 1, 0).toISOString().slice(0, 10);

export const mockMessages: Message[] = [
  {
    id: "1",
    username: "@glowbysarah",
    platform: "instagram",
    comment: "Do you offer hydrafacials? How much do they cost?",
    aiReply: "Yes! Our HydraFacials start at $149 and include a full cleanse, extract, and hydration treatment. Want me to send you the booking link? 💜",
    status: "review",
    confidenceScore: 94,
    detectedIntent: "Service Inquiry",
    tags: ["Hot Lead", "Pricing Question", "Booking Intent"],
    timestamp: "2 min ago",
  },
  {
    id: "2",
    username: "@thefitnesscollective",
    platform: "instagram",
    comment: "Do you offer payment plans for your coaching program?",
    aiReply: "Absolutely! We offer flexible 3 and 6-month payment plans with 0% interest. Send us a DM and we'll get you set up right away 🙌",
    status: "review",
    confidenceScore: 88,
    detectedIntent: "Pricing Question",
    tags: ["Hot Lead", "Pricing Question"],
    timestamp: "5 min ago",
  },
  {
    id: "3",
    username: "@shopnovathread",
    platform: "facebook",
    comment: "Do you ship internationally? I'm in the UK!",
    aiReply: "Yes we do! We ship to over 40 countries. International orders typically arrive in 7–12 business days. DM us your address and we'll confirm shipping costs for you 🌍",
    status: "auto",
    confidenceScore: 97,
    detectedIntent: "Shipping Inquiry",
    tags: ["Booking Intent"],
    timestamp: "12 min ago",
  },
  {
    id: "4",
    username: "@realestatebypriya",
    platform: "instagram",
    comment: "Is now a good time to buy in this market? I'm a first-time buyer.",
    aiReply: "Great question! Every market is different — book a free 15-min call with our team and we'll walk you through exactly what's available in your budget right now. No pressure, just clarity 🏠",
    status: "review",
    confidenceScore: 79,
    detectedIntent: "Consultation Request",
    tags: ["Hot Lead", "Booking Intent"],
    timestamp: "18 min ago",
  },
  {
    id: "5",
    username: "@agencyowner_mark",
    platform: "instagram",
    comment: "What's your pricing for bulk packages? We have 10 clients who might be interested.",
    aiReply: "We love working with agencies! Our bulk packages start at $499/mo for up to 10 accounts. DM us for a custom quote and we'll build something that works for your team.",
    status: "auto",
    confidenceScore: 91,
    detectedIntent: "B2B Inquiry",
    tags: ["Hot Lead", "Pricing Question"],
    timestamp: "25 min ago",
  },
  {
    id: "6",
    username: "@chefmarcelokitchen",
    platform: "instagram",
    comment: "Can I book a private dining experience for 12 people?",
    aiReply: "Absolutely! We do private events for groups of 8–20. DM us your date, dietary needs, and vibe and we'll put together a custom menu for you 🍽️",
    status: "auto",
    confidenceScore: 96,
    detectedIntent: "Event Booking",
    tags: ["Hot Lead"],
    timestamp: "31 min ago",
  },
  {
    id: "7",
    username: "@thelocalboutique.co",
    platform: "facebook",
    comment: "I ordered 4 days ago and haven't received a shipping update. This is frustrating.",
    aiReply: "We're so sorry for the delay! That's not the experience we want for you. Please DM us your order number and we'll track it down and prioritize getting this resolved for you today 💛",
    status: "escalated",
    confidenceScore: 45,
    detectedIntent: "Complaint",
    tags: ["Complaint Risk"],
    timestamp: "45 min ago",
  },
  {
    id: "8",
    username: "@digitalmarketer_leo",
    platform: "instagram",
    comment: "How does the AI reply system work exactly? I'm worried about it sounding robotic.",
    aiReply: "Great question! Our AI learns your exact brand voice, tone, and offers — then you review every reply before it posts. Nothing goes live without your approval. Want to see a demo? 🤖✨",
    status: "review",
    confidenceScore: 85,
    detectedIntent: "Product Curiosity",
    tags: ["Pricing Question"],
    timestamp: "1 hr ago",
  },
  {
    id: "9",
    username: "@hairbytamara_",
    platform: "instagram",
    comment: "Is there a free trial?",
    aiReply: "Yes! We offer a 14-day free trial — no credit card required. You can set up your brand voice, connect Instagram, and see real results before paying a cent. Start here: autom8ig.io 🚀",
    status: "auto",
    confidenceScore: 98,
    detectedIntent: "Trial Interest",
    tags: ["Hot Lead", "Booking Intent"],
    timestamp: "1 hr ago",
  },
  {
    id: "10",
    username: "@pilateswithpaola",
    platform: "instagram",
    comment: "Do you have online classes or is it in-person only?",
    aiReply: "We offer both! In-person classes in Miami and a full online library with 100+ on-demand videos. You can mix and match — DM us and we'll help you pick the right plan 🧘‍♀️",
    status: "auto",
    confidenceScore: 99,
    detectedIntent: "Product Feature",
    tags: ["General Inquiry"],
    timestamp: "2 hr ago",
  },
  {
    id: "11",
    username: "@medspa_miami",
    platform: "instagram",
    comment: "How many replies per month on the basic plan?",
    aiReply: "Our Growth plan includes 1,000 replies/month — enough for most active accounts. Need more? Our Scale plan handles unlimited. Check our pricing: autom8ig.io/billing 💪",
    status: "auto",
    confidenceScore: 93,
    detectedIntent: "Pricing Question",
    tags: ["Pricing Question"],
    timestamp: "2 hr ago",
  },
  {
    id: "12",
    username: "@lawoffice_sanchez",
    platform: "facebook",
    comment: "Is my data safe? What do you do with my client information?",
    aiReply: "Your data is 100% secure. We use enterprise-grade encryption and only request the minimum permissions needed to read comments and post replies. We never sell your data. Privacy is our top priority.",
    status: "sent",
    confidenceScore: 88,
    detectedIntent: "Trust & Safety",
    tags: ["General Inquiry"],
    timestamp: "3 hr ago",
  },
];

export const mockUsage = {
  repliesUsed: 340,
  limit: 500,
  periodStart,
  periodEnd,
  dailyCounts: [8,12,5,14,18,22,9,11,16,20,13,7,19,24,17,21,15,10,23,18,12,25,14,9,16,20,11,8,18,15],
};

export const mockPlans = [
  {
    id: "starter",
    name: "Starter",
    price: 9,
    period: "week",
    replyLimit: 250,
    features: ["250 AI replies/month", "1 Instagram account", "Basic brand voice", "Human review queue", "Email support"],
    popular: false,
  },
  {
    id: "growth",
    name: "Growth",
    price: 29,
    period: "week",
    replyLimit: 1000,
    features: ["1,000 AI replies/month", "3 accounts (IG + FB)", "Advanced Brand Brain", "Priority review queue", "Analytics dashboard", "Priority support"],
    popular: true,
  },
  {
    id: "scale",
    name: "Scale",
    price: 99,
    period: "week",
    replyLimit: -1,
    features: ["Unlimited replies", "Unlimited accounts", "Multi-client dashboard", "White-label options", "Dedicated account manager", "API access"],
    popular: false,
  },
];

export const mockBrandProfile = {
  businessName: "Luxe Glow Medspa",
  industry: "medspa",
  websiteUrl: "https://luxeglow.com",
  description: "Premier medical spa in Los Angeles offering HydraFacials, Botox, laser treatments, and wellness services.",
  tones: ["Professional", "Luxe", "Friendly"],
  customToneNotes: "Warm and welcoming but always professional. Never use slang. Always end with a CTA.",
  services: [
    { name: "HydraFacial", priceRange: "$149 - $249" },
    { name: "Botox", priceRange: "$12/unit" },
    { name: "Laser Hair Removal", priceRange: "$199+" },
  ],
  ctaKeywords: ["price", "how much", "cost", "available", "book", "appointment", "free trial"],
  escalationRules: "Do not discuss specific medical conditions, diagnoses, or treatment outcomes. Escalate complaints or negative experiences to human team.",
  emojiAllowed: true,
  language: "English",
  formalityLevel: 65,
};

export const mockUser = {
  id: "mock-user-id",
  name: "Demo User",
  email: "demo@autom8ig.io",
  plan: "starter" as const,
  connectedInstagram: false,
  brandSetupComplete: true,
};

export const mockActivityFeed = [
  { id: "1", text: "Auto-replied to @glowbysarah on Instagram", time: "2 min ago", type: "reply" },
  { id: "2", text: "@agencyowner_mark opened the booking link you shared", time: "8 min ago", type: "lead" },
  { id: "3", text: "7 new comments received from your last post", time: "15 min ago", type: "inbox" },
  { id: "4", text: "@thelocalboutique.co escalated — needs human review", time: "45 min ago", type: "escalation" },
  { id: "5", text: "Auto-replied to 12 comments overnight", time: "8 hr ago", type: "reply" },
];
